import Head from "next/head";

export default function SEO() {
  return (
    <Head>
      <title>Dutchie</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@200;300;400;600&display=swap"
        rel="stylesheet"
      />
    </Head>
  );
}
